export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_ITINERARIES = "FETCH_ITINERARIES";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const FETCH_CREATEACCOUNT = "FETCH_CREATEACCOUNT";
export const FETCH_LOGIN = "FETCH_LOGIN";
export const USER_LOADED = "USER_LOADED";

